# Generated by Django 2.0.5 on 2018-08-13 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='佚名', max_length=20, verbose_name='姓名')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客评论',
                'verbose_name_plural': '博客评论',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='Nexus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200, verbose_name='Nexu_name')),
            ],
            options={
                'verbose_name': 'Nexu',
                'verbose_name_plural': 'Nexu',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=500, verbose_name='Reference')),
                ('l_name_exp', models.CharField(max_length=500, verbose_name='Description')),
                ('l_name_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nexus', verbose_name='R_name')),
            ],
            options={
                'verbose_name': 't1_name',
                'verbose_name_plural': 't1_name',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='Nickname')),
                ('description', models.CharField(default='', max_length=150, verbose_name='Description')),
                ('pwd', models.CharField(max_length=32, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is_active')),
            ],
            options={
                'verbose_name': 'Username',
                'verbose_name_plural': 'Username',
            },
        ),
        migrations.CreateModel(
            name='Wlibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='TheoremName')),
                ('exp', models.TextField(verbose_name='explain')),
                ('mcdc_1', models.IntegerField(default=0, verbose_name='mcdc_1')),
                ('mcdc_2', models.IntegerField(default=0, verbose_name='mcdc_2')),
                ('ref', models.CharField(default='', max_length=500, verbose_name='Reference')),
                ('publish', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'verbose_name': 'Wlibrary',
                'verbose_name_plural': 'Wlibrary',
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='app.Wlibrary', verbose_name='t1_name'),
        ),
        migrations.AddField(
            model_name='relation',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='app.Wlibrary', verbose_name='t2_name'),
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='wlibrary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Wlibrary', verbose_name='定理'),
        ),
    ]
