# Generated by Django 2.0.2 on 2018-07-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='wlibrary',
            name='Wlabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Label'),
        ),
    ]
