# Generated by Django 2.0.2 on 2018-07-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180719_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='wlibrary',
            name='Wlabel',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='relation',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='app.Wlibrary'),
        ),
        migrations.AddField(
            model_name='relation',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='app.Wlibrary'),
        ),
    ]
