# Generated by Django 2.0.2 on 2018-07-24 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180720_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nexus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200, verbose_name='Nexu_name')),
            ],
            options={
                'verbose_name': 'Nexu',
                'verbose_name_plural': 'Nexu',
            },
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 't1_name', 'verbose_name_plural': 't1_name'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Username', 'verbose_name_plural': 'Username'},
        ),
        migrations.AlterField(
            model_name='relation',
            name='l_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nexus', verbose_name='R_name'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='app.Wlibrary', verbose_name='t1_name'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='app.Wlibrary', verbose_name='t2_name'),
        ),
    ]
