# Generated by Django 2.0.2 on 2018-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180724_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='Realname'),
        ),
    ]
